env:
  LIC: ${{secrets.LIC}}
  SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
  OPENAI_GPT_API: ${{secrets.OPENAI_GPT_API}}
  
  

name: Betterscan Scan
on: [push]
jobs:
  Betterscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create folder
        run: |
          mkdir .checkmate
          touch .checkmate/dummy
          tree
          ls -la
      - name: Store state
        uses: actions/upload-artifact@v3.1.2
        with:
          name: state
          path: .checkmate
      - name: Get state
        uses:  actions/download-artifact@v2.1.1
        with:
          name: state
      - name: Betterscan Scan
        uses: topcodersonline/betterscan@v3
      - name: Store state
        uses: actions/upload-artifact@v3.1.2
        with:
          name: state
          path: .checkmate
      - name: Upload the SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report.sarif
